### ISSUE TITLE
Moving off a floating bomb onto a dam leaves you in mid-air

### ISSUE THREAD

**Issue by lordmauve** [larryhastings/pyweek26#12]
I think I'm actually standing on the dam here, but I got moved into this mid-air spot:

![day7-10](https://user-images.githubusercontent.com/617224/47608466-2ccc5080-da26-11e8-9861-20e32dd316e6.png)

**Comment by larryhastings** [comment]
wfm.  maybe there are more conditions?  if you give me a repro case I will fix.

![day7-1](https://user-images.githubusercontent.com/14175923/47608977-73e92000-d9eb-11e8-91f2-b463ce29dd3f.png)

**Comment by lordmauve** [comment]
The bomb is floating northwards in current
