### ISSUE TITLE
Feature request: use speech bubbles for level complete / player died

### ISSUE THREAD

**Issue by larryhastings** [larryhastings/pyweek26#7]
Instead of a big label over the screen, it'd be more in theme to have a speech bubble appear, in the same way that we have dialog at the beginning, for level complete or player death.

Maybe something like:

Level complete:
 <(  GOOD JOB!  )

Player death:
 <(  WHAT JUST HAPPENED, JIM?  )

**Comment by lordmauve** [comment]
Fixed in b142750f3f344df323bf0d60e26ea404c3c10ca6
